### PR TITLE
Some improvements

### PR DESCRIPTION
**Pull request by Windvis**
Good job! I only did some minor thingies.

Things I changed:

- fix tiny syntax error which prevented the engine from booting
- change the styling setup so appuniversum isn't included twice if the host app also imports it
- include ember-cli-moment-shim. This would otherwise thrown an error if the host app didn't have that installed.
- Setup the dummy app for easier engine development

### CODE REVIEW

**Review by aatauil — COMMENTED** [review]
I tested it turning on lazy loading but the app crashed. I dont know if we really need it but I think its a nice extra for later

**Review by aatauil — APPROVED** [review]
All good and working and can be merged :)

**Comment by Windvis** [comment]
> I tested it turning on lazy loading but the app crashed. I dont know if we really need it but I think its a nice extra for later

Interesting. What did the error say?

**Comment by aatauil** [comment]
> > I tested it turning on lazy loading but the app crashed. I dont know if we really need it but I think its a nice extra for later
> 
> Interesting. What did the error say?

Had something to do with "monkey-patch-ember-computed" cant really find what that is or does online for some reason

**Comment by Windvis** [comment]
It seems to be a similar issue as this: https://github.com/sir-dunxalot/ember-tooltips/pull/420
[
ember-macro-helpers also uses `app.import`](https://github.com/kellyselden/ember-macro-helpers/blob/b14c4d9d32fb7f6d4090b37525014d4a88057f5e/index.js#L9) to import that file, so that probably needs to be changed in a similar way to support lazy engines.

**Pull request merged**
