### PR TITLE
Some release-it changes

### PR DESCRIPTION
**Pull request by Windvis**
While looking at https://github.com/lblod/frontend-dashboard I noticed the deps were brought in by this engine.

- moves release-it to devDeps
- use `GITHUB_AUTH` for the Github plugin so only 1 environment variable is needed

### CODE REVIEW

**Comment by Windvis** [comment]
unrelated to this PR, but I think the ember-power-select and `@ember/legacy-built-in-components` aren't used either?

**Comment by benjay10** [comment]
`@ember/legacy-built-in-components` is a requirement for ember-engines to work ([see this issue](https://github.com/ember-engines/ember-engines/issues/813)). I tried and it is definitely still needed.

`ember-power-select` can be dropped.

`ember-concurrency-decorators` where also missing. Strange that this has not been noticed before.

**Review by benjay10 — APPROVED** [review]
Of course I cannot test the release mechanism, but these changes seems sound.
(As an aside: shouldn't more package also appear as a peerDependency?)

**Comment by Windvis** [comment]
Ah, I didn't know about the ember-engines issue, thanks! It's strange they don't include it themselves if they still depend on it though.

>  (As an aside: shouldn't more package also appear as a peerDependency?)

Maybe, yes, I'm not sure how that works in engines. Worth experimenting with, probably.

Also, I would have pushed those changes in a new PR since they are not related to this one 😄. I just mentioned it here because I noticed it while moving things around.

It would also be better to simply drop ember-concurrency-decorators and switch to ember-concurrency.

**Comment by benjay10** [comment]
I understand, but I couldn't let this PR go through while the app was not building/running. A new PR is just a lot of administration to me for adding a single package.

**Review by nvdk — APPROVED** [review]
looks good to me, apologies didn't see I added them as true dependencies :+1:

**Comment by nvdk** [comment]
> It would also be better to simply drop ember-concurrency-decorators and switch to ember-concurrency.

agreed there, perhaps in a separate PR?

**Pull request merged**
